---


dietpi_home_path: "/mnt/user_data"
comics_path: "/mnt/comics"
books_path: "/mnt/books"
incomplete_path: "/mnt/incomplete"
downloads_path: "/mnt/downloads"
music_path: "/mnt/music"
hole_path: "/mnt/hole"
video_path: "/mnt/video"
anime_path: "/mnt/anime"
tv_archive_path: "/mnt/tv_archive"
tv_path: "/mnt/tv"
private_path: "/mnt/private"

mount_nfs_path:
  - "/mnt/user_data"
  - "/mnt/comics"
  - "/mnt/books"
  - "/mnt/incomplete"
  - "/mnt/downloads"
  - "/mnt/music"
  - "/mnt/hole"
  - "/mnt/video"
  - "/mnt/anime"
  - "/mnt/tv_archive"
  - "/mnt/tv"
  - "/mnt/private"