---

- name: Ensure minimal package for ansible
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - net-tools
      - python3
      - python3-apt
      - nfs-common
      - libipset-dev #Needed for keepalived
  tags:
    - init
    - init_install