---

- name: Ensure minimal package for ansible
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - net-tools
      - python3
      - python3-apt
      - nfs-common
      - libipset-dev #Needed for keepalived
      - python3-jsondiff #Needed for ansible stack module
      - python3-yaml #Needed for ansible stack module
  tags:
    - init
    - init_install