---

- name: Ensure minimal package for ansible
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - net-tools
      - python3
      - python3-apt
      - nfs-common
      - libipset-dev #Needed for keepalived
      - python3-jsondiff #Needed for ansible stack module
      - python3-yaml #Needed for ansible stack module
      - python3-pip
      - open-iscsi #Needed for Iscsi
      - multipath-tools #Needed for mutipath
      - snmpd
  tags:
    - init
    - init_install

- name: Install pip python3
  command: pip3 install pip --upgrade
  tags:
    - init
    - init_pip

- name: Install docker python SDK
  command: pip install docker
  tags:
    - init
    - init_pip_docker
    
# apt-get install python-pip
# pip install pip --upgrade
# apt-get install python-setuptools NOK
# pip2 install docker-compose-swarm-mode NOK
# pip2 install request NOK
# pip install docker
# pip install jsondiff
# apt-get install python3-pip
# pip3 install --upgrade pip
# pip install docker