---

- name: Perform a discovery and show available target nodes
  open_iscsi:
    show_nodes: yes
    discover: yes
    portal: '{{NAS2}}'
  register: isisci_reg

- debug: msg="{{isisci_reg.output}}"


- name: Login to Iscsi
  open_iscsi:
    login: 'yes'
    target: 'iqn.2000-01.com.synology:stor2.Swarm.ad5871fae5'
    auto_node_startup: 'yes'
    portal: '{{NAS2}}'


