---

- name: Unmount
  mount:
    path: "{{ item }}"
    state: unmounted
  with_items: 
    - "{{ mount_nfs_path }}"
  tags:
    - mount
    - mount-umount-dir

- name: Ensure local mount dir
  file:
    path: "{{ item }}"
    state: directory
  with_items: 
    - "{{ mount_nfs_path }}"
  tags:
    - mount
    - mount-ensure-dir

- set_fact:
    hosts_content: "{{ lookup('template', 'templates/fstab.j2') }}"
  tags :
    - mount
    - mount_facts

- blockinfile:
    dest: /etc/fstab
    content: '{{ hosts_content }}'
    insertafter: EOF
    state: present
    validate: "/bin/mount -fav %s"
  notify: Mount share
  tags :
    - mount
    - mount_share

