---
# Check_mk agent for Librenms
#Clone Check_mk
- name: Clone Check_mk Librenms agent
  git:
    repo: 'https://github.com/librenms/librenms-agent.git'
    dest: /opt
    clone: yes
    update: yes
  tags:
    - init_snmp_librenms
    - init_snmp_librenms_git

- name : Copy check_mk_agent
  copy:
    src: /opt/librenms-agent/check_mk_agent
    dest: /usr/bin/check_mk_agent
    remote_src: yes
    owner: root
    group: root
    mode: '0755'
  tags:
    - init_snmp_librenms
    - init_snmp_librenms_check_mk_agent

- name: Copy check_mk_agent service
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system
    remote_src: yes
    owner: root
    group: root
    mode: '0644'
  with_items:
    - '/opt/librenms-agent/check_mk@.service'
    - '/opt/librenms-agent/check_mk.socket'
  notify: Start and enable check_mk_agent
  tags:
    - init_snmp_librenms
    - init_snmp_librenms_check_mk_agent_service

- block:
  - name: Template Librenms distro SNMP extend
    template:
      src: snmp/librenms/distro.sh.j2
      dest: /usr/bin/distro
      mode: 0755
      owner: root
      group: root
  - name: Template Librenms OS Uupdate SNMP extend
    template:
      src: snmp/librenms/osupdate.sh.j2
      dest: /etc/snmp/osupdate
      mode: 0755
      owner: root
      group: root
  - name: Template Librenms Ntp Client SNMP extend
    template:
      src: snmp/librenms/ntp-client.sh.j2
      dest: /etc/snmp/ntp-client
      mode: 0755
      owner: root
      group: root
  - name: Template Librenms ifAlias_persist script
    template:
      src: snmp/ifAlias_persist.pl.j2
      dest: /usr/local/bin/ifAlias_persist
      mode: 0755
      owner: root
      group: root
  - name: Template Librenms Asus Tinker Board S SNMP extend
    template:
      src: snmp/librenms/tinker.sh.j2
      dest: /etc/snmp/tinker.sh
      mode: 0755
      owner: root
      group: root
    when: board == 'tinker'
  - name: Template Librenms Raspberry Pi SNMP extend
    template:
      src: snmp/librenms/raspberry.sh.j2
      dest: /etc/snmp/raspberry.sh
      mode: 0755
      owner: root
      group: root
    when: board == 'rpi'
  tags:
    - init_snmp_librenms
    - init_snmp_librenms_agent_script
    
- name: Configure snmpd for Librenms
  template:
    src: snmp/librenms/snmpd.conf.j2
    dest: /etc/snmp/snmpd.conf
    mode: 0644
    owner: root
    group: root
  notify: Restart snmpd
  tags:
    - init_snmp_librenms
    - init_snmp_librenms_snmp_conf

- block:
  - name: Ensure minimal Armbian packages for Librenms
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - ntp
        - xinetd
    when: ansible_os_family == "Debian"
  - name: Template xinetd obserium script
    template:
      src: snmp/observium_agent_xinetd.sh.j2
      dest: /etc/xinetd.d/observium_agent_xinetd
      mode: 0644
  tags:
    - init
    - init_install

- block:
  - name: Template Observium agent
    template:
      src: snmp/observium_agent.sh.j2
      dest: /usr/bin/observium_agent
      mode: 0755
  - name: Ensure agent's directory
    file:
      path: "{{ item }}"
      mode: directory
      recurse: yes
    with_items:
      - /usr/lib/observium_agent/scripts-available
      - /usr/lib/observium_agent/scripts-enabled
  - name: Copy specific scripts
    template:
      src: "{{ item }}"
      dest: 
      mode: 0755
    with_items:
      - {src: "snmp/observium_os.sh.j2", dest: "/usr/lib/observium_agent/scripts-available/os"}
      # to do other script + link to enabled

