---

- name: Slack notify
  slack:
    channel: "{{ slack_channel }}"
    color: 'warning'
    icon_url: 'https://www.ansible.com/favicon.ico'
    msg: 'Rebooting swarm'
    token: "{{ slack_token }}"
    username: 'Ansible'
  run_once: true
  when: slack_notify
  tags:
    - reboot_notify

- name: Rebooting host
  reboot:
