---
- name: Get docker info
  shell: docker info
  register: docker_info
  changed_when: false

- name: Create primary swarm manager
  shell: docker swarm init --advertise-addr {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}
  when:
    - "docker_info.stdout.find('Swarm: inactive') != -1"
    - inventory_hostname in groups['manager1']

- name: Get docker swarm manager token
  shell: docker swarm join-token -q manager
  register: manager_token
  when: inventory_hostname in groups['manager1']

- name: Get docker swarm worker token
  shell: docker swarm join-token -q worker
  register: worker_token
  when: inventory_hostname in groups['manager1']

- name: Label assignment
  docker_node:
    hostname: "{{ansible_hostname}}"
    labels:
      arch: "{{arch}}"
      board: "{{board}}"
  when: inventory_hostname in groups['manager1']