---

- name: Join as a manager
  shell: "docker swarm join --token {{ hostvars[item]['manager_token']['stdout'] }} {{ hostvars[item]['ansible_default_ipv4']['address'] }}:2377"
  with_items: "{{ groups['manager1'] }}"
  when:
    - "docker_info.stdout.find('Swarm: inactive') != -1"
    - inventory_hostname in groups['managers']
  retries: 6
  delay: 30