---
- name: Shutdown host
  command: /sbin/shutdown -h now

- name: Slack notify
  slack:
    channel: "{{ slack_channel }}"
    color: 'danger'
    icon_url: 'https://www.ansible.com/favicon.ico'
    msg: 'Shutdown swarm'
    token: "{{ slack_token }}"
    username: 'Ansible'
  run_once: true
  when: slack_notify

- name: wait go down
  local_action: wait_for host={{ ansible_ssh_host }} port=22 state=stopped