---

- name: Slack notify
  slack:
    channel: "{{ slack_channel }}"
    color: 'good'
    icon_url: 'https://www.ansible.com/favicon.ico'
    msg: "{{ ansible_hostname }} is online"
    token: "{{ slack_token }}"
    username: 'Ansible Check'
  run_once: true
  when: slack_notify
  tags:
    - check_notify