---

- name: Check host availability
  ping:
  delegate_to: localhost
  register: ping_result
  ignore_errors: yes


- name: Slack notify on success
  slack:
    channel: "{{ slack_channel }}"
    color: 'good'
    icon_url: 'https://www.ansible.com/favicon.ico'
    msg: "{{ ansible_hostname }} is online"
    token: "{{ slack_token }}"
    username: 'Ansible Check'
  when: slack_notify and
        ping_result|success
  tags:
    - check_notify

- name: Slack notify on failure
  slack:
    channel: "{{ slack_channel }}"
    color: 'danger'
    icon_url: 'https://www.ansible.com/favicon.ico'
    msg: "{{ ansible_hostname }} is down"
    token: "{{ slack_token }}"
    username: 'Ansible Check'
  when: slack_notify and
        ping_result|pong
  tags:
    - check_notify