---

- name: Check host availability
  command: ping -c1 {{ inventory_hostname }}
  delegate_to: localhost
  register: ping_result
  ignore_errors: yes

- name: retreive docker status
  command: systemctl status docker
  register: docker_status
  when: ping_result|success

- name: Slack notify on success
  delegate_to: localhost
  slack:
    channel: "{{ slack_channel }}"
    color: 'good'
    icon_url: 'https://www.ansible.com/favicon.ico'
    msg: "*{{ inventory_hostname|UPPER }}* is online :smile:. Docker status {{docker_status.stdout}}"
    token: "{{ slack_token }}"
    username: 'Ansible Check'
  ignore_errors: yes
  when: slack_notify and
        ping_result|success
  tags:
    - check_notify

- name: clearing host errors
  meta: clear_host_errors

- name: Bad
  delegate_to: localhost
  slack:
    channel: "{{ slack_channel }}"
    color: 'danger'
    icon_url: 'https://www.ansible.com/favicon.ico'
    msg: "*{{ inventory_hostname|UPPER }}* is down :skull: :sob:. You have to do somethings !"
    token: "{{ slack_token }}"
    username: 'Ansible Check'
  when: slack_notify and
        ping_result|failed
  tags:
    - check_notify