---

- name: Get docker info
  shell: docker info
  register: docker_info
  changed_when: false

- name: Leaving swarm
  command: |
        docker swarm leave --force
  when:
    - "docker_info.stdout.find('Swarm: inactive') != -1"
  tags:
    - swarm_reset
    - swarm_reset_leave

- name: Prune system
  command: |
        docker system prune -a -f
  tags:
    - swarm_reset
    - swarm_reset_prune

- name: Restart docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
  tags:
    - swarm_reset
    - swarm_reset_docker
