---

- name: Leaving swarm
  docker_swarm:
    state: absent
    force: true
  tags:
    - swarm_reset
    - swarm_reset_leave

- name: Prune system
  command: |
    docker container prune -f |
    docker image prune -f |
    docker volume prune -f
  tags:
    - swarm_reset
    - swarm_reset_prune

- name: Restart docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
  tags:
    - swarm_reset
    - swarm_reset_docker
