---

- name: Leaving swarm
  docker_swarm:
    state: absent
    force: true
  tags:
    - swarm_reset
    - swarm_reset_leave

- name: Stop docker
  systemd:
    name: docker
    state: stopped
  tags:
    - swarm_reset
    - swarm_reset_docker_stop

- name: Delete docker related
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - "/var/lib/docker"
    - "/mnt/dietpi_userdata"
  tags:
    - swarm_reset
    - swarm_reset_docker_delete

#- name: Prune system
#  command: "{{ item }}"
#  with_items:
#    - docker system prune -af
#  ignore_errors: yes
#  tags:
#    - swarm_reset
#    - swarm_reset_prune

- name: Restart docker
  systemd:
    name: docker
    state: started
    daemon_reload: yes
  tags:
    - swarm_reset
    - swarm_reset_docker
