---

- name: Leaving swarm
  docker_swarm:
    state: absent
    force: true
  tags:
    - swarm_reset
    - swarm_reset_leave

- name: Prune system
  command: "{{ item }}"
  with_items:
    - docker system prune -af
  ignore_errors: yes
  tags:
    - swarm_reset
    - swarm_reset_prune

- name: Restart docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
  tags:
    - swarm_reset
    - swarm_reset_docker
