---

- name: check reachable hosts
  hosts: all
  gather_facts: no
  tasks:
    - command: ping -c1 {{ inventory_hostname }}
      delegate_to: localhost
      register: ping_result
      ignore_errors: yes
    - group_by: key=reachable
      when: ping_result|success

- name: Play role on rechable
  hosts: reachable
  gather_facts: yes
  vars_files:
    - "../env_vars/main.yml"
  roles:
    - check