---

- name: Install keepalived
  apt:
    name: keepalived
    state: present
  when: ansible_os_family == "Debian"
  tags:
    - keepalived-install

- name: Check service
  template: 
    src: check_script.sh.j2 
    dest: /etc/keepalived/check_script.sh
    mode: 0755
    owner: root
    group: root
  tags:
    - keepalived-check-service
  notify: Restart enabled Keepalived

- name: Keepalived config
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  tags:
    - keepalived-config

- name: Start keepalived service
  systemd:
    name: keepalived
    enabled: yes
    state: restarted
  when: ansible_os_family == "Debian"
  tags:
    - keepalived-start

- name: Start keepalived service on alpine
  service:
    name: keepalived
    state: restarted
  when: arch == "x86"
  tags:
    - keepalived-start