---

- name: Mount share
  command: mount -a

- name: Restart snmpd
  systemd:
    name: snmpd
    enabled: yes
    state: restarted

- name: Restart multipathd
  systemd:
    name: multipathd
    enabled: yes
    state: restarted

- name: Enable reload and start autofs service
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: autofs

- name: Start and enable check_mk_agent
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: check_mk.socket