---

- name: Create a Traefik network
  docker_network:
    name: traefik_public
    attachable: yes
    driver: overlay
    ipam_config:
      - subnet: 172.16.200.0/24

- name: Create a common network
  docker_network:
    name: common
    attachable: yes
    driver: overlay
    ipam_config:
      - subnet: 172.16.100.0/24