---
# Ensure directories

- name: Ensure prune directory
  file:
    path: "{{ docker_prune_logfile_dir }}"
    state: directory
    mode: 0755
  tags:
    - docker-cron
    - docker-cron_prune_dir

# Docker prune volume dangling

- name: Deploy volume prune job
  template:
    src: docker-prune-volume.sh.j2
    dest: "{{ docker_prune_logfile_dir }}/docker-prune-volume.sh"
    mode: u+x
  tags:
    - docker-cron
    - docker-cron_prune_volume_script

- name: Ensure docker prune volume log file
  file:
    path: "{{ docker_prune_volume_logfile_path }}"
    state: touch
  tags:
    - docker-cron
    - docker-cron_prune_volume_logfile

- name: Copy docker prune volume logrotate
  template:
    src: docker-prune-volume-log.j2
    dest: "{{ logrotate_path }}/docker-prune-volume-log"
  tags:
    - docker-cron
    - docker-cron_prune_volume_logrotate

- name: Install prune cron
  cron:
    name: "Docker prune dangling volume"
    user: root
    hour: "9"
    minute: "40"
    job: "{{ docker_prune_logfile_dir }}/docker-prune-volume.sh >> {{ docker_prune_logfile_dir }}/prune-volume-log.log"
    state: present
    cron_file: prune-volume
  tags:
    - docker-cron
    - docker-cron_prune_volume_install

# Docker prune system

- name: Deploy system prune job
  template:
    src: docker-prune-system.sh.j2
    dest: "{{ docker_prune_logfile_dir }}/docker-prune-system.sh"
    mode: u+x
  tags:
    - docker-cron
    - docker-cron_prune_system_script

- name: Ensure docker prune system log file
  file:
    path: "{{ docker_prune_system_logfile_path }}"
    state: touch
  tags:
    - docker-cron
    - docker-cron_prune_system_logfile

- name: Copy docker prune system logrotate
  template:
    src: docker-prune-system-log.j2
    dest: "{{ logrotate_path }}/docker-prune-system-log"
  tags:
    - docker-cron
    - docker-cron_prune_volume_logrotate

- name: Install prune cron
  cron:
    name: "Docker prune system"
    user: root
    hour: "9"
    minute: "45"
    job: "{{ docker_prune_logfile_dir }}/docker-prune-system.sh >> {{ docker_prune_logfile_dir }}/prune-system-log.log"
    state: present
    cron_file: prune-system
  tags:
    - docker-cron
    - docker-cron_prune_system_install
