---

- name: Create parent docker directory
  file:
    path: "{{docker_mount_nfs_path_parent}}"
    state: directory
  tags:
    - docker-conf
    - docker-conf-parent-dir

- name: Create directory
  file:
    path: "{{docker_mount_nfs_path}}"
    state: directory
  tags:
    - docker-conf
    - docker-conf-dir

- name: Create docker conf
  template:
    src: daemon.json.j2
    dest: "{{docker_path}}daemon.json"
    owner: root
    group: root
    mode: 0644
  notify: Restart Docker
  tags:
    - docker-conf
    - docker-conf-daemon
