---

- name: Ensure mandatory directories
  file:
    path: "{{docker_conf_path}}/Registry"
    state: directory
  tags:
  - docker_registry_dir

#- name: Creating Secret
#  command: docker run --entrypoint htpasswd registry:2.6 -Bbn {{registry_user}} {{registry_password}} | docker secret create registry_htpasswd -
#  tags:
#  - docker_registry_secret

- name: Genreating Secret
  docker_container:
    name: secretbuilderregistry
    state: present
    image: registry:2.6
    entrypoint: htpasswd
    command: -Bbn {{registry_user}} {{registry_password}} | docker secret create registry_htpasswd -
  register: generated_secret
  tags:
  - docker_registry_secret_generate

- name: Create secret registry_htpasswd
  docker_secret:
    name: registry_htpasswd
    data: "generated_secret.stdout"
    state: present
  tags:
  - docker_registry_secret_create

- name: Stopping container
  docker_container:
    name: secretbuilderregistry
    state: absent
    cleanup: yes
  tags:
  - docker_registry_secret_clean

- name: Template 'Docker-Registry' compose file
  template:
    src: docker-registry.yml.j2
    dest: "{{docker_conf_path}}/Docker-registry/docker-registry.yml"

- name: Deploy 'Docker-Registry' stack from file
  docker_stack:
    state: present
    name: docker-registry
    compose:
     - "{{docker_conf_path}}/Docker-registry/docker-registry.yml"