- name: Encrypt username/password
  docker_container:
    name: htpasswd
    image: registry:2
    entrypoint: htpasswd -Bbn {{ item.username }} {{ item.password }}
    detach: false
  register: output

- name: Create file, if it does not exist
  file:
    name: "{{ registry_auth_path }}/{{ registry_auth_file }}"
    state: touch

- name: Remove user from password file, if exists
  lineinfile:
    dest: "{{ registry_auth_path }}/{{ registry_auth_file }}"
    regexp: '^{{ item.username }}'
    state: absent 

- name: Add user to password file
  lineinfile:
    dest: "{{ registry_auth_path }}/{{ registry_auth_file }}"
    line: "{{ output.stdout | replace('\n', '') }}"