---
- name: Template 'Lidarr' compose file
  template:
    src: lidarr.yml.j2
    dest: "{{docker_conf_path}}/Lidarr/lidarr.yml"
    owner: '1024'
    group: '100'

- name: Deploy 'Lidarr' stack from file
  docker_stack:
    state: present
    name: lidarr
    compose:
     - "{{docker_conf_path}}/Lidarr/lidarr.yml"


