---

- import_tasks: traefik.yml
  tags:
    - stack
    - stack_traefik

- import_tasks: visualizer.yml
  tags:
    - stack
    - stack_visualizer

- import_tasks: docker-cleanup.yml
  tags:
    - stack
    - stack_docker-cleanup

- import_tasks: registry.yml
  tags:
    - stack
    - stack_registry

- import_tasks: swarmprom.yml
  tags:
    - stack
    - stack_swarmprom

- import_tasks: portainer.yml
  tags:
    - stack
    - stack_portainer

- import_tasks: heimdall.yml
  tags:
    - stack
    - stack_heimdall

- import_tasks: whoami.yml
  tags:
    - stack
    - stack_whoami

- import_tasks: ubooquity.yml
  tags:
    - stack
    - stack_ubooquity
