---

- import_tasks: traefik.yml
  tags:
    - stack
    - stack_traefik

- import_tasks: traefik-forward-auth.yml
  tags:
    - stack
    - stack_traefik-forward-auth

- import_tasks: visualizer.yml
  tags:
    - stack
    - stack_visualizer

- import_tasks: docker-cleanup.yml
  tags:
    - stack
    - stack_docker-cleanup

- import_tasks: registry.yml
  tags:
    - stack
    - stack_registry

- import_tasks: swarmprom.yml
  tags:
    - stack
    - stack_swarmprom

- import_tasks: portainer.yml
  tags:
    - stack
    - stack_portainer

- import_tasks: heimdall.yml
  tags:
    - stack
    - stack_heimdall

- import_tasks: whoami.yml
  tags:
    - stack
    - stack_whoami

- import_tasks: ubooquity.yml
  tags:
    - stack
    - stack_ubooquity

- import_tasks: hydra2.yml
  tags:
    - stack
    - stack_hydra2

- import_tasks: sabnzbd.yml
  tags:
    - stack
    - stack_sabnzbd