---
- name: Template 'Mylar' compose file
  template:
    src: mlr.yml.j2
    dest: "{{docker_conf_path}}/Mlr/mlr.yml"
    owner: '1024'
    group: '100'

- name: Deploy 'Mylar' stack from file
  docker_stack:
    state: present
    name: mlr
    compose:
     - "{{docker_conf_path}}/Mlr/mlr.yml"


