---
- name: Template 'Radarr' compose file
  template:
    src: radarr.yml.j2
    dest: "{{docker_conf_path}}/Radarr/radarr.yml"
    owner: '1024'
    group: '100'

- name: Deploy 'Radarr' stack from file
  docker_stack:
    state: present
    name: radarr
    compose:
     - "{{docker_conf_path}}/Radarr/radarr.yml"


