---
- name: Template 'Swarmpit' compose file
  template:
    src: swarmpit.yml.j2
    dest: "{{docker_conf_path}}/Swarmpit/swarmpit.yml"
    owner: '1024'
    group: '100'

- name: Deploy 'Swarmpit' stack from file
  docker_stack:
    state: present
    name: swarmpit
    compose:
     - "{{docker_conf_path}}/Swarmpit/swarmpit.yml"


