---

- name: Template 'Traefik' compose file
  template:
    src: traefik-forward-auth.yml.j2
    dest: "{{docker_conf_path}}/Traefik-swarm/traefik-forward-auth.yml"
    owner: '1024'
    group: '100'

# - name: Ensure acme.json
#   file:
#     path: "{{docker_conf_path}}/Traefik-swarm/acme.json"
#     state: touch
#     mode : 0600
#     modification_time: preserve
#     access_time: preserve

- name: Login to private registry
  docker_login:
    registry: registry.{{domain}}
    username: "{{registry_user}}"
    password: "{{registry_password}}"

- name: Deploy 'Traefik' stack from file
  docker_stack:
    state: present
    name: traefik
    compose:
     - "{{docker_conf_path}}/Traefik-swarm/traefik-forward-auth.yml"
