---

- name: Create parent docker directory
  file:
    path: "{{docker_mount_nfs_path_parent}}"
    owner: root
    group: docker
    mode: 0755
    state: directory
  tags:
    - docker-conf
    - docker-conf-parent-dir

- name: Create directory
  file:
    path: "{{docker_mount_nfs_path}}"
    owner: root
    group: docker
    mode: 0755
    state: directory
  tags:
    - docker-conf
    - docker-conf-dir

- name: Ensure docker group on docker directories
  file:
    path: "{{docker_mount_nfs_path}}"
    owner: root
    group: docker
    mode: g+rwX
    recurse: yes
  tags:
    - docker-conf
    - docker-conf-dir

- name: Create docker conf
  template:
    src: daemon.json.j2
    dest: "{{docker_path}}daemon.json"
    owner: root
    group: root
    mode: 0644
  notify: Restart Docker-CE
  tags:
    - docker-conf
    - docker-conf-daemon
